#!/usr/bin/env python3
import json
import os
import sys


def main():
    with open("builtin.json") as fp:
        dl = json.load(fp)

        for item in dl:
            file = os.path.join(os.path.dirname(__file__), item["file"])
            if not os.path.exists(file):
                print(f"file is not exists: {file}", file=sys.stderr)
                sys.exit(2)


if __name__ == '__main__':
    main()
