#!/usr/bin/env python3

import json

with open("builtin.json") as fp:
    dl = json.load(fp)


def s_n(x) -> str:  # sort by name
    return x["name"]


dl = sorted(dl, key=s_n)

with open("builtin.json", "w") as fp:
    data = json.dumps(dl, indent=2, ensure_ascii=False)
    fp.write(data)
    fp.write("\n")
