#!/usr/bin/env python3

import json
from pprint import pprint

with open("builtin.json") as fp:
    dl = json.load(fp)

def s_n(x): # sort by name
    return x["name"]

sorted(dl, key=s_n)

pprint(dl)
